spring.application.name=doctor-service
spring.config.import=optional:configserver:http://localhost:8888

# Resilience4j rate limiter configuration for doctor search
resilience4j.ratelimiter.instances.searchDoctorLimit.limit-for-period=5
resilience4j.ratelimiter.instances.searchDoctorLimit.limit-refresh-period=10s
resilience4j.ratelimiter.instances.searchDoctorLimit.timeout-duration=0
